# podman play kube pod_config_secret.yaml
# podman pod logs hello-pod
# podman pod restart -l
kind: Secret
metadata:
  name: my-secret
data:
  PASSWORD: cG9kbWFu

---
kind: ConfigMap
metadata:
  name: my-config
data:
  CONFIG_KEY: "MyConfigValue"
  cfg.json: |
    {
        "isTlsEnabled": false,
        "externalDatabase": false,
        "ospgIpAddress": "\300\250d*",
        "osgpPortNumber": 12125
    }

---
kind: ConfigMap
metadata:
  name: platform-key
data:
  platform_ecdsa_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjiRRokgWsPZZ3q2voqH7ipdvPsdJ
    neegPBcozM+zN9rZg8RGeZt2pMdFAFlpfBQn37H1D4lvDYK+MSpv6ERONw==
    -----END PUBLIC KEY-----

---
kind: Pod
metadata:
  name: hello-pod
spec:
  restartPolicy: Never  # Options: Always, OnFailure, Never
  containers:
    - name: hello-container
      image: hello-static
      envFrom:
        - configMapRef:
            name: my-config
            optional: false
        - secretRef:
            name: my-secret
      volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: platform-volume
          mountPath: /platform   
      args:
        - "--noTLS"
  volumes:
    - name: config-volume
      configMap:
        name: my-config 
    - name: platform-volume
      configMap:
        name: platform-key 
