# podman play kube pod_config_secret.yaml
# podman pod logs hello-pod
# podman pod restart -l
kind: Secret
metadata:
  name: my-secret
data:
  PASSWORD: cG9kbWFu

---
kind: ConfigMap
metadata:
  name: my-config
data:
  CONFIG_KEY: "MyConfigValue"
  cfg.json: |
    {
        "isTlsEnabled": false,
        "externalDatabase": false,
        "ospgIpAddress": "\300\250d*",
        "osgpPortNumber": 12125
    }

---
kind: Pod
metadata:
  name: hello-pod
spec:
  restartPolicy: Never  # Options: Always, OnFailure, Never
  containers:
    - name: hello-container
      image: hello-static
      envFrom:
        - configMapRef:
            name: my-config
            optional: false
        - secretRef:
            name: my-secret
      volumeMounts:
        - name: config-volume
          mountPath: /config      
      args:
        - "--noTLS"
  volumes:
    - name: config-volume
      configMap:
        name: my-config  
